import type { TalismanDefinition } from '../types';

/**
 * Talismans accumulate for the whole run — there are no equipment slots.
 * Each is pure data: trigger + conditions + effects (see types/effects.ts for the DSL).
 * Bespoke logic is referenced by id through `{ kind: 'custom' }` (effects/custom.ts).
 */
export const TALISMANS: TalismanDefinition[] = [
  // ───────────────────────────── Matching / Month control
  {
    id: 'moon-greeting',
    number: 1,
    name: '달맞이',
    nameEn: 'Moon Greeting',
    rarity: 'common',
    tags: ['month'],
    glyph: '迎',
    description: '매 스테이지 첫 짝맞춤: 목표 점수의 6% 보너스 (최소 +50).',
    trigger: 'CARD_MATCHED',
    conditions: [],
    effects: [{ kind: 'addScore', value: { scalar: 'stageTarget', times: 0.06, min: 50 }, label: '달맞이' }],
    limit: { perStage: 1 },
  },
  {
    id: 'leap-month',
    number: 2,
    name: '윤달 부적',
    nameEn: 'Leap Month Charm',
    rarity: 'uncommon',
    tags: ['month'],
    glyph: '閏',
    description: '스테이지 시작 시 손패 무작위 1장이 이번 스테이지 동안 만월(어떤 달과도 짝)이 됨.',
    trigger: 'STAGE_STARTED',
    conditions: [],
    effects: [{ kind: 'tempEnhance', target: { from: 'hand', filter: { joker: false }, pick: 'random' }, enhancement: 'wildMonth' }],
    shout: '윤달!',
  },
  {
    id: 'two-moons',
    number: 3,
    name: '두 개의 달',
    nameEn: 'Two Moons',
    rarity: 'uncommon',
    tags: ['month', 'mutation'],
    glyph: '兩',
    description: '두 달 이상인 카드: 획득 점수 ×1.35, 그 카드가 발동시킨 족보 ×1.35.',
    trigger: 'SCORE_CAPTURE',
    conditions: [{ kind: 'subject', filter: { multiMonth: true } }],
    effects: [{ kind: 'captureMult', value: 1.35 }],
    extraSpecs: [
      {
        trigger: 'SCORE_JOKBO',
        conditions: [{ kind: 'triggerCard', filter: { multiMonth: true } }],
        effects: [{ kind: 'jokboMult', value: 1.35 }],
      },
    ],
  },
  {
    id: 'full-moon',
    number: 4,
    name: '보름달',
    nameEn: 'Full Moon',
    rarity: 'uncommon',
    tags: ['month'],
    glyph: '滿',
    description: '한 스테이지에 같은 달 카드를 3장 획득하면 그 달이 이번 스테이지 동안 ×1.5 (획득 점수 + 그 달 카드가 발동시킨 족보).',
    trigger: 'CARD_CAPTURED',
    conditions: [{ kind: 'custom', id: 'monthReachedThree' }],
    effects: [{ kind: 'custom', id: 'fullMoonMonth' }],
    shout: '보름달',
  },
  {
    id: 'crescent',
    number: 5,
    name: '초승달',
    nameEn: 'Crescent',
    rarity: 'common',
    tags: ['month'],
    glyph: '初',
    description: '각 달에서 처음 획득한 카드는 이번 스테이지 동안 레벨 +1.',
    trigger: 'CARD_CAPTURED',
    conditions: [{ kind: 'firstOfMonthThisStage' }, { kind: 'subject', filter: { joker: false } }],
    effects: [{ kind: 'upgradeCard', target: { from: 'subject', pick: 'all' }, levels: 1, scope: 'stage' }],
    shout: '초승달 +1',
  },
  {
    id: 'torn-calendar',
    number: 6,
    name: '달력 찢기',
    nameEn: 'Torn Calendar',
    rarity: 'mythic',
    tags: ['month', 'thin'],
    glyph: '裂',
    description: '덱에 카드가 한 장도 없는 달 1개마다 전체 배율 +0.25.',
    trigger: 'SCORE_ALL',
    conditions: [],
    effects: [{ kind: 'globalMultAdd', value: { scalar: 'monthsMissingFromDeck', times: 0.25 } }],
  },
  {
    id: 'moon-echo',
    number: 7,
    name: '달의 메아리',
    nameEn: 'Echo of the Moon',
    rarity: 'rare',
    tags: ['month', 'retrigger'],
    glyph: '月',
    description: '연속된 두 번의 짝맞춤이 같은 달이면, 두 번째 짝맞춤으로 획득한 카드의 획득 효과가 다시 발동.',
    trigger: 'CAPTURE_RESOLVED',
    conditions: [{ kind: 'custom', id: 'consecutiveSameMonth' }],
    effects: [{ kind: 'retriggerCapture' }],
    shout: '달의 메아리',
  },
  {
    id: 'twelve-months',
    number: 8,
    name: '열두 달',
    nameEn: 'Twelve Months',
    rarity: 'rare',
    tags: ['month', 'rainbow'],
    glyph: '曆',
    description: '스테이지 종료 시 서로 다른 9개 이상의 달을 획득했다면 스테이지 점수 +30%.',
    trigger: 'STAGE_ENDING',
    conditions: [{ kind: 'scalar', value: { scalar: 'distinctMonthsCaptured' }, op: '>=', than: 9 }],
    effects: [{ kind: 'addScore', value: { scalar: 'stageScore', times: 0.3 }, label: '열두 달', applyGlobal: false }],
  },
  {
    id: 'season-trade',
    number: 9,
    name: '한철 장사',
    nameEn: 'Seasonal Trade',
    rarity: 'uncommon',
    tags: ['month'],
    glyph: '商',
    description: '덱에서 가장 흔한 달: 그 달 카드의 획득 점수 ×1.4, 그 달 카드가 발동시킨 족보 ×1.4.',
    trigger: 'SCORE_CAPTURE',
    conditions: [{ kind: 'subject', filter: { mostCommonMonth: true } }],
    effects: [{ kind: 'captureMult', value: 1.4 }],
    extraSpecs: [
      {
        trigger: 'SCORE_JOKBO',
        conditions: [{ kind: 'triggerCard', filter: { mostCommonMonth: true } }],
        effects: [{ kind: 'jokboMult', value: 1.4 }],
      },
    ],
  },
  {
    id: 'season-wind',
    number: 10,
    name: '계절 바람',
    nameEn: 'Seasonal Wind',
    rarity: 'common',
    tags: ['month', 'exchange'],
    glyph: '風',
    description: '스테이지 종료 시 획득한 서로 다른 달 3개마다 다음 스테이지 교환 +1.',
    trigger: 'STAGE_ENDING',
    conditions: [],
    effects: [{ kind: 'nextStageExchange', value: { scalar: 'distinctMonthsCaptured', floorDiv: 3 } }],
  },

  // ───────────────────────────── Ribbon builds
  {
    id: 'blue-thread',
    number: 11,
    name: '푸른 실',
    nameEn: 'Blue Thread',
    rarity: 'common',
    tags: ['ribbon', 'cheongdan'],
    glyph: '靑',
    description: '청단 점수 ×1.5.',
    trigger: 'SCORE_JOKBO',
    conditions: [{ kind: 'jokbo', ids: ['cheongdan'] }],
    effects: [{ kind: 'jokboMult', value: 1.5 }],
  },
  {
    id: 'red-thread',
    number: 12,
    name: '붉은 실',
    nameEn: 'Red Thread',
    rarity: 'common',
    tags: ['ribbon', 'hongdan'],
    glyph: '紅',
    description: '홍단 점수 ×1.5.',
    trigger: 'SCORE_JOKBO',
    conditions: [{ kind: 'jokbo', ids: ['hongdan'] }],
    effects: [{ kind: 'jokboMult', value: 1.5 }],
  },
  {
    id: 'white-knot',
    number: 13,
    name: '흰 매듭',
    nameEn: 'White Knot',
    rarity: 'common',
    tags: ['ribbon', 'chodan'],
    glyph: '白',
    description: '초단 점수 ×1.5.',
    trigger: 'SCORE_JOKBO',
    conditions: [{ kind: 'jokbo', ids: ['chodan'] }],
    effects: [{ kind: 'jokboMult', value: 1.5 }],
  },
  {
    id: 'tricolor-thread',
    number: 14,
    name: '삼색실',
    nameEn: 'Tricolor Thread',
    rarity: 'rare',
    tags: ['ribbon', 'rainbow'],
    glyph: '三',
    description: '한 스테이지에 홍단·청단·초단을 모두 완성하면 이번 스테이지 전체 배율 ×2 (세 번째 완성부터 적용).',
    trigger: 'JOKBO_COMPLETED',
    conditions: [
      { kind: 'jokboGroup', groups: ['ribbonSet'] },
      { kind: 'scalar', value: { scalar: 'ribbonSetsActivatedThisStage' }, op: '>=', than: 3 },
    ],
    effects: [{ kind: 'stageGlobalMult', value: 2 }],
    limit: { perStage: 1 },
    shout: '삼색실 ×2',
  },
  {
    id: 'long-ribbon',
    number: 15,
    name: '긴 띠',
    nameEn: 'Long Ribbon',
    rarity: 'common',
    tags: ['ribbon'],
    glyph: '長',
    description: '띠 족보: 5장을 넘는 띠 1장마다 +60 고정 점수.',
    trigger: 'SCORE_JOKBO',
    conditions: [{ kind: 'jokbo', ids: ['ribbon'] }],
    effects: [{ kind: 'flat', value: { scalar: 'ribbonsCaptured', offset: -5, times: 60, min: 0 } }],
  },
  {
    id: 'knot-master',
    number: 16,
    name: '매듭 장인',
    nameEn: 'Knot Master',
    rarity: 'uncommon',
    tags: ['ribbon'],
    glyph: '結',
    description: '강화가 붙은 띠의 카드 파워 +15.',
    trigger: 'CARD_POWER',
    conditions: [{ kind: 'subject', filter: { categories: ['ribbon'], enhanced: true } }],
    effects: [{ kind: 'power', value: 15 }],
  },
  {
    id: 'blue-wave',
    number: 17,
    name: '푸른 물결',
    nameEn: 'Blue Ripple',
    rarity: 'uncommon',
    tags: ['ribbon', 'cheongdan'],
    glyph: '波',
    description: '청단 발동 후 이번 스테이지에 띠를 획득할 때마다 청단 마지막 점수의 15% (최소 50) 추가.',
    trigger: 'CAPTURE_RESOLVED',
    conditions: [
      { kind: 'jokboActive', id: 'cheongdan' },
      { kind: 'subject', filter: { categories: ['ribbon'] } },
    ],
    effects: [
      {
        kind: 'addScore',
        value: { scalar: 'jokboLastScore', arg: 'cheongdan', times: 0.15, min: 50 },
        label: '푸른 물결',
        applyGlobal: false,
      },
    ],
  },
  {
    id: 'red-sunset',
    number: 18,
    name: '붉은 노을',
    nameEn: 'Red Sunset',
    rarity: 'uncommon',
    tags: ['ribbon', 'hongdan'],
    glyph: '霞',
    description: '홍단이 완성(또는 추가 세트)될 때마다 덱의 1~3월 카드 무작위 1장 영구 레벨 +1.',
    trigger: 'JOKBO_TRIGGERED',
    conditions: [
      { kind: 'jokbo', ids: ['hongdan'] },
      { kind: 'reason', reasons: ['complete', 'increment'] },
    ],
    effects: [
      {
        kind: 'upgradeCard',
        target: { from: 'deck', filter: { months: [1, 2, 3], joker: false }, pick: 'random' },
        levels: 1,
        scope: 'run',
      },
    ],
    shout: '붉은 노을',
  },
  {
    id: 'wildflower-knot',
    number: 19,
    name: '들꽃 매듭',
    nameEn: 'Wildflower Knot',
    rarity: 'common',
    tags: ['ribbon', 'chodan', 'exchange'],
    glyph: '野',
    description: '초단이 완성(또는 추가 세트)될 때마다 교환 +1.',
    trigger: 'JOKBO_TRIGGERED',
    conditions: [
      { kind: 'jokbo', ids: ['chodan'] },
      { kind: 'reason', reasons: ['complete', 'increment'] },
    ],
    effects: [{ kind: 'grantExchange', value: 1 }],
    shout: '교환 +1',
  },
  {
    id: 'broken-string',
    number: 20,
    name: '끊어진 끈',
    nameEn: 'Broken String',
    rarity: 'rare',
    tags: ['ribbon', 'retrigger'],
    glyph: '斷',
    description: '스테이지 종료 시 띠 세트 족보(홍단/청단/초단) 중 정확히 하나만 발동했다면 그 족보를 두 번 재발동.',
    trigger: 'STAGE_ENDING',
    conditions: [{ kind: 'scalar', value: { scalar: 'ribbonSetsActivatedThisStage' }, op: '==', than: 1 }],
    effects: [{ kind: 'retrigger', target: 'onlyRibbonSetThisStage', times: 2 }],
    shout: '끊어진 끈',
  },

  // ───────────────────────────── Bright / Animal
  {
    id: 'radiance',
    number: 21,
    name: '광채',
    nameEn: 'Luster',
    rarity: 'common',
    tags: ['bright'],
    glyph: '輝',
    description: '광이 포함된 족보 ×1.3.',
    trigger: 'SCORE_JOKBO',
    conditions: [{ kind: 'member', filter: { bright: true } }],
    effects: [{ kind: 'jokboMult', value: 1.3 }],
  },
  {
    id: 'five-lights',
    number: 22,
    name: '다섯 빛',
    nameEn: 'Five Lights',
    rarity: 'rare',
    tags: ['bright'],
    glyph: '五',
    description: '이번 스테이지에 처음 획득하는 종류의 광마다 이번 스테이지 전체 배율 +0.1.',
    trigger: 'CARD_CAPTURED',
    conditions: [{ kind: 'subject', filter: { bright: true } }, { kind: 'firstOfIdentityThisStage' }],
    effects: [{ kind: 'stageGlobalMultAdd', value: 0.1 }],
    shout: '빛 +0.1',
  },
  {
    id: 'rain-umbrella',
    number: 23,
    name: '비광의 우산',
    nameEn: "Rain Bright's Umbrella",
    rarity: 'common',
    tags: ['bright'],
    glyph: '傘',
    description: '비광이 더 이상 삼광 점수를 깎지 않음 (비삼광도 3점).',
    trigger: 'RULES',
    conditions: [],
    effects: [{ kind: 'rule', rule: 'rainBrightPenalty', value: false }],
  },
  {
    id: 'birdcage',
    number: 24,
    name: '새장',
    nameEn: 'Birdcage',
    rarity: 'uncommon',
    tags: ['godori', 'animal'],
    glyph: '籠',
    description: '고도리 점수 ×1.75.',
    trigger: 'SCORE_JOKBO',
    conditions: [{ kind: 'jokbo', ids: ['godori'] }],
    effects: [{ kind: 'jokboMult', value: 1.75 }],
  },
  {
    id: 'flock',
    number: 25,
    name: '새떼',
    nameEn: 'Flock',
    rarity: 'uncommon',
    tags: ['godori', 'animal'],
    glyph: '群',
    description: '고도리 발동 후 이번 스테이지에 열끗을 획득할 때마다 +100 × 고도리 레벨.',
    trigger: 'CAPTURE_RESOLVED',
    conditions: [
      { kind: 'jokboActive', id: 'godori' },
      { kind: 'subject', filter: { categories: ['animal'] } },
    ],
    effects: [{ kind: 'addScore', value: { scalar: 'jokboLevel', arg: 'godori', times: 100 }, label: '새떼' }],
  },
  {
    id: 'beast-tracks',
    number: 26,
    name: '짐승 발자국',
    nameEn: 'Beast Tracks',
    rarity: 'uncommon',
    tags: ['animal'],
    glyph: '跡',
    description: '열끗이 포함된 획득(짝맞춤 한 번)을 연달아 할수록 콤보 +1 (열끗 없는 획득을 하면 초기화). 열끗 획득 점수 ×(1+0.25×콤보), 열끗·고도리 족보 배율 +0.2×콤보.',
    trigger: 'CARD_CAPTURED',
    conditions: [],
    effects: [{ kind: 'custom', id: 'beastCombo' }],
    extraSpecs: [
      {
        trigger: 'SCORE_CAPTURE',
        conditions: [{ kind: 'subject', filter: { categories: ['animal'] } }],
        effects: [{ kind: 'captureMult', value: { scalar: 'counter', arg: 'animalCombo', offset: 4, times: 0.25, min: 1 } }],
      },
      {
        trigger: 'SCORE_JOKBO',
        conditions: [{ kind: 'jokbo', ids: ['animal', 'godori'] }],
        effects: [{ kind: 'jokboMultAdd', value: { scalar: 'counter', arg: 'animalCombo', times: 0.2 } }],
      },
    ],
  },
  {
    id: 'boar-tusk',
    number: 27,
    name: '멧돼지 엄니',
    nameEn: 'Boar Tusk',
    rarity: 'uncommon',
    tags: ['animal'],
    glyph: '牙',
    description: '7월 열끗의 레벨 파워 ×3.',
    trigger: 'CARD_POWER',
    conditions: [{ kind: 'subject', filter: { categories: ['animal'], months: [7] } }],
    effects: [{ kind: 'levelPowerMult', value: 3 }],
  },
  {
    id: 'butterfly-dream',
    number: 28,
    name: '나비 꿈',
    nameEn: 'Butterfly Dream',
    rarity: 'rare',
    tags: ['animal', 'ribbon', 'retrigger'],
    glyph: '蝶',
    description: '6월 열끗을 획득하면, 다음에 획득하는 띠의 획득 효과와 그 띠가 발동시킨 족보가 한 번 더 발동.',
    trigger: 'CARD_CAPTURED',
    conditions: [{ kind: 'subject', filter: { categories: ['animal'], months: [6] } }],
    effects: [{ kind: 'setFlag', flag: 'butterfly', value: true }],
    shout: '나비 꿈',
    extraSpecs: [
      {
        trigger: 'CAPTURE_RESOLVED',
        conditions: [
          { kind: 'flag', flag: 'butterfly', value: true },
          { kind: 'subject', filter: { categories: ['ribbon'] } },
        ],
        effects: [
          { kind: 'setFlag', flag: 'butterfly', value: false },
          { kind: 'retriggerCapture' },
          { kind: 'custom', id: 'retriggerJokboOfSubject' },
        ],
        shout: '나비 꿈!',
      },
    ],
  },
  {
    id: 'deer-path',
    number: 29,
    name: '사슴의 길',
    nameEn: 'Deer Path',
    rarity: 'common',
    tags: ['animal'],
    glyph: '鹿',
    description: '10월 열끗을 획득하면 다음 턴까지 더미 위 2장을 미리 봄.',
    trigger: 'CARD_CAPTURED',
    conditions: [{ kind: 'subject', filter: { categories: ['animal'], months: [10] } }],
    effects: [{ kind: 'preview', value: 2 }],
    shout: '사슴의 길',
  },
  {
    id: 'geese-flight',
    number: 30,
    name: '기러기 떼',
    nameEn: 'Flight of Geese',
    rarity: 'uncommon',
    tags: ['animal', 'godori'],
    glyph: '雁',
    description: '8월 열끗: 덱의 복제 카드 1장마다 파워 +10.',
    trigger: 'CARD_POWER',
    conditions: [{ kind: 'subject', filter: { categories: ['animal'], months: [8] } }],
    effects: [{ kind: 'power', value: { scalar: 'duplicatesInDeck', times: 10 } }],
  },

  // ───────────────────────────── Pi / Thin deck
  {
    id: 'dust-gather',
    number: 31,
    name: '티끌 모아',
    nameEn: 'Dust Gathering',
    rarity: 'common',
    tags: ['pi'],
    glyph: '塵',
    description: '피 족보의 기본 점수 +50%.',
    trigger: 'SCORE_JOKBO',
    conditions: [{ kind: 'jokbo', ids: ['pi'] }],
    effects: [{ kind: 'baseMult', value: 1.5 }],
  },
  {
    id: 'double-trade',
    number: 32,
    name: '쌍피 장사',
    nameEn: 'Double-Pi Trade',
    rarity: 'uncommon',
    tags: ['pi'],
    glyph: '雙',
    description: '규칙 변경: 쌍피가 피 2장이 아니라 3장으로 셈.',
    trigger: 'RULES',
    conditions: [],
    effects: [{ kind: 'rule', rule: 'doublePiValue', value: 3, mode: 'max' }],
  },
  {
    id: 'dusty',
    number: 33,
    name: '먼지투성이',
    nameEn: 'Dust Covered',
    rarity: 'uncommon',
    tags: ['pi'],
    glyph: '埃',
    description: '이번 스테이지에 피를 5장 획득할 때마다 덱의 무작위 피 1장 영구 레벨 +1.',
    trigger: 'CARD_CAPTURED',
    conditions: [
      { kind: 'subject', filter: { categories: ['pi'] } },
      { kind: 'scalar', value: { scalar: 'piCardsCaptured' }, op: 'multipleOf', than: 5 },
    ],
    effects: [
      { kind: 'upgradeCard', target: { from: 'deck', filter: { categories: ['pi'], joker: false }, pick: 'random' }, levels: 1, scope: 'run' },
    ],
    shout: '먼지투성이',
  },
  {
    id: 'emptying',
    number: 34,
    name: '비움',
    nameEn: 'Emptying',
    rarity: 'rare',
    tags: ['thin'],
    glyph: '空',
    description: '시작 덱에서 제거한 카드 5장마다 전체 배율 +0.15.',
    trigger: 'SCORE_ALL',
    conditions: [],
    effects: [{ kind: 'globalMultAdd', value: { scalar: 'cardsRemovedFromStart', floorDiv: 5, times: 0.15 } }],
  },
  {
    id: 'light-hand',
    number: 35,
    name: '가벼운 패',
    nameEn: 'Light Hand',
    rarity: 'common',
    tags: ['thin', 'exchange'],
    glyph: '輕',
    description: '덱이 35장 이하이면 스테이지 시작 시 교환 +1.',
    trigger: 'STAGE_STARTED',
    conditions: [{ kind: 'scalar', value: { scalar: 'deckSize' }, op: '<=', than: 35 }],
    effects: [{ kind: 'grantExchange', value: 1 }],
    shout: '가벼운 패',
  },
  {
    id: 'sword-cut',
    number: 36,
    name: '칼로 벤 패',
    nameEn: 'Sword-Cut Deck',
    rarity: 'rare',
    tags: ['thin', 'retrigger'],
    glyph: '劍',
    description: '덱이 30장 이하이면 매 스테이지 첫 족보 발동이 한 번 더 재발동.',
    trigger: 'JOKBO_TRIGGERED',
    conditions: [
      { kind: 'scalar', value: { scalar: 'deckSize' }, op: '<=', than: 30 },
      { kind: 'reason', reasons: ['complete', 'increment'] },
    ],
    effects: [{ kind: 'retrigger', target: 'event', times: 1 }],
    limit: { perStage: 1 },
    shout: '칼로 벤 패',
  },
  {
    id: 'empty-seat',
    number: 37,
    name: '빈자리',
    nameEn: 'Empty Seat',
    rarity: 'uncommon',
    tags: ['thin'],
    glyph: '席',
    description: '이 부적을 얻은 뒤 카드를 제거할 때마다 모든 족보 고정 점수 +25 (영구, 런 전체).',
    trigger: 'CARD_REMOVED',
    conditions: [],
    effects: [{ kind: 'counter', counter: 'removed', op: 'add', value: 1, scope: 'talisman' }],
    extraSpecs: [
      {
        trigger: 'SCORE_JOKBO',
        conditions: [],
        effects: [{ kind: 'flat', value: { scalar: 'talismanCounter', arg: 'removed', times: 25 } }],
      },
    ],
  },
  {
    id: 'blood-sea',
    number: 38,
    name: '피바다',
    nameEn: 'Sea of Pi',
    rarity: 'rare',
    tags: ['pi'],
    glyph: '血',
    description: '피 가치 10을 넘긴 뒤 피를 획득할 때마다 점점 커지는 보너스 (+40, +80, +120…).',
    trigger: 'CAPTURE_RESOLVED',
    conditions: [
      { kind: 'subject', filter: { categories: ['pi'] } },
      { kind: 'scalar', value: { scalar: 'piValueCaptured' }, op: '>', than: 10 },
    ],
    effects: [
      { kind: 'addScore', value: { scalar: 'counter', arg: 'bloodSea', offset: 1, times: 40 }, label: '피바다' },
      { kind: 'counter', counter: 'bloodSea', op: 'add', value: 1, scope: 'stage' },
    ],
  },
  {
    id: 'scarecrow',
    number: 39,
    name: '허수아비',
    nameEn: 'Scarecrow',
    rarity: 'common',
    tags: ['thin'],
    glyph: '案',
    description: '공허 강화 카드를 제거·희생할 때 보상 ×2.',
    trigger: 'RULES',
    conditions: [],
    effects: [],
  },
  {
    id: 'weeding',
    number: 40,
    name: '잡초 뽑기',
    nameEn: 'Weeding',
    rarity: 'common',
    tags: ['pi', 'thin', 'economy'],
    glyph: '草',
    description: '각 상점에서 처음 제거하는 피 카드는 무료 (제거 비용 환불).',
    trigger: 'SHOP',
    conditions: [],
    effects: [{ kind: 'priceMult', service: 'removalPi', value: 0, firstOnly: true }],
  },

  // ───────────────────────────── Engine / Joker / Economy
  {
    id: 'goblin-club',
    number: 41,
    name: '도깨비 방망이',
    nameEn: 'Goblin Club',
    rarity: 'uncommon',
    tags: ['joker'],
    glyph: '棒',
    description: '매 스테이지 첫 조커 획득 시 이번에 획득한 카드 무작위 1장 영구 레벨 +1 (빈 조커면 3장).',
    trigger: 'CARD_CAPTURED',
    conditions: [{ kind: 'subject', filter: { joker: true } }],
    effects: [
      {
        kind: 'upgradeCard',
        target: { from: 'captured', filter: { joker: false }, pick: 'random' },
        levels: 1,
        scope: 'run',
        count: 1,
      },
    ],
    limit: { perStage: 1 },
    shout: '도깨비 방망이',
    extraSpecs: [
      {
        trigger: 'CARD_CAPTURED',
        conditions: [{ kind: 'subject', filter: { joker: true, jokerForm: 'empty' } }],
        effects: [
          {
            kind: 'upgradeCard',
            target: { from: 'captured', filter: { joker: false }, pick: 'random' },
            levels: 1,
            scope: 'run',
            count: 2,
          },
        ],
        limit: { perStage: 1 },
        shout: '빈 조커 ×3',
      },
    ],
  },
  {
    id: 'clown-mask',
    number: 42,
    name: '광대탈',
    nameEn: 'Clown Mask',
    rarity: 'mythic',
    tags: ['joker'],
    glyph: '面',
    description: '조커가 획득될 때 직전에 획득한 조커 아닌 카드의 점수 태그(달·종류)를 얻음.',
    trigger: 'CARD_CAPTURED',
    conditions: [{ kind: 'subject', filter: { joker: true } }],
    effects: [{ kind: 'copyProfile', from: 'lastCapturedNonJoker' }],
    shout: '광대탈',
  },
  {
    id: 'empty-mask',
    number: 43,
    name: '빈 가면',
    nameEn: 'Empty Mask',
    rarity: 'rare',
    tags: ['joker'],
    glyph: '假',
    description: '빈 조커의 강화 효과가 3배 (강화 파워, 황금 배율, 메아리 횟수 등).',
    trigger: 'RULES',
    conditions: [],
    effects: [],
  },
  {
    id: 'echo-drum',
    number: 44,
    name: '메아리 북',
    nameEn: 'Echo Drum',
    rarity: 'rare',
    tags: ['retrigger'],
    glyph: '鼓',
    description: '매 스테이지 첫 재발동이 재발동을 하나 더 만듦.',
    trigger: 'RETRIGGER_REQUESTED',
    conditions: [],
    effects: [{ kind: 'retrigger', target: 'event', times: 1 }],
    limit: { perStage: 1 },
    shout: '메아리 북',
  },
  {
    id: 'chain-knot',
    number: 45,
    name: '연쇄 매듭',
    nameEn: 'Chain Knot',
    rarity: 'uncommon',
    tags: ['retrigger', 'rainbow'],
    glyph: '鎖',
    description: '한 연쇄 안에서 발동한 서로 다른 효과 출처 1개마다 연쇄 배율 +0.1.',
    trigger: 'SCORE_ALL',
    conditions: [],
    effects: [{ kind: 'globalMultAdd', value: { scalar: 'chainDistinctSources', times: 0.1 } }],
  },
  {
    id: 'broken-mirror',
    number: 46,
    name: '깨진 거울',
    nameEn: 'Broken Mirror',
    rarity: 'rare',
    tags: ['retrigger'],
    glyph: '破',
    description: '한 턴에 정확히 한 종류의 족보만 득점했다면 턴 종료 시 그 족보를 한 번 더 재발동. 피·띠·열끗처럼 장수로 세는 족보는 제외.',
    trigger: 'TURN_ENDED',
    conditions: [{ kind: 'custom', id: 'onlyScoredIsSetJokbo' }],
    effects: [{ kind: 'retrigger', target: 'onlyScoredThisTurn', times: 1 }],
    shout: '깨진 거울',
  },
  {
    id: 'abacus',
    number: 47,
    name: '장사꾼 주판',
    nameEn: "Merchant's Abacus",
    rarity: 'common',
    tags: ['economy'],
    glyph: '算',
    description: '스테이지 클리어 시 초과 점수 25%마다 엽전 +1 (최대 +10).',
    trigger: 'STAGE_CLEARED',
    conditions: [],
    effects: [{ kind: 'coins', value: { scalar: 'overkillPercent', floorDiv: 25, max: 10 } }],
    shout: '주판',
  },
  {
    id: 'lucky-pouch',
    number: 48,
    name: '복주머니',
    nameEn: 'Lucky Pouch',
    rarity: 'common',
    tags: ['economy'],
    glyph: '囊',
    description: '상점에서 3번째 구매마다 무작위 일반 보상 (엽전, 카드 강화, 일반 부적).',
    trigger: 'ITEM_PURCHASED',
    conditions: [],
    effects: [{ kind: 'custom', id: 'luckyPouch' }],
  },
  {
    id: 'gamblers-hand',
    number: 49,
    name: '도박사의 손',
    nameEn: "Gambler's Hand",
    rarity: 'uncommon',
    tags: ['economy'],
    glyph: '賭',
    description: '상점에서 가장 비싼 상품을 사면 효과 +25%: 레벨 상승은 +1레벨, 그 외에는 가격의 25% 환급.',
    trigger: 'SHOP',
    conditions: [],
    effects: [],
  },
  {
    id: 'endless-rite',
    number: 50,
    name: '끝없는 굿판',
    nameEn: 'Endless Rite',
    rarity: 'mythic',
    tags: ['retrigger'],
    glyph: '巫',
    description: '한 연쇄가 8번의 발동에 도달하면 이후 그 연쇄의 모든 점수 ×2.',
    trigger: 'SCORE_ALL',
    conditions: [{ kind: 'scalar', value: { scalar: 'chainTriggerCount' }, op: '>=', than: 8 }],
    effects: [{ kind: 'globalMult', value: 2 }],
    shout: '끝없는 굿판 ×2',
  },

  // ───────────────────────────── Exchange extras (section 5 examples)
  {
    id: 'swift-hands',
    number: 51,
    name: '빠른 손',
    nameEn: 'Swift Hands',
    rarity: 'common',
    tags: ['exchange'],
    glyph: '手',
    description: '매 스테이지 교환 +1.',
    trigger: 'RULES',
    conditions: [],
    effects: [{ kind: 'rule', rule: 'exchangesPerStage', value: 1, mode: 'add' }],
  },
  {
    id: 'pi-sieve',
    number: 52,
    name: '피 체',
    nameEn: 'Pi Sieve',
    rarity: 'common',
    tags: ['exchange', 'pi'],
    glyph: '篩',
    description: '스테이지마다 한 번, 피 카드는 교환 횟수를 쓰지 않고 교환 가능.',
    trigger: 'RULES',
    conditions: [],
    effects: [],
  },
  {
    id: 'blossom-scout',
    number: 53,
    name: '꽃구경',
    nameEn: 'Blossom Scout',
    rarity: 'common',
    tags: ['exchange', 'hongdan'],
    glyph: '櫻',
    description: '3월 카드를 교환으로 버리면 다음 턴까지 더미 위 3장을 미리 봄.',
    trigger: 'EXCHANGE_USED',
    conditions: [{ kind: 'subject', filter: { months: [3] } }],
    effects: [{ kind: 'preview', value: 3 }],
    shout: '꽃구경',
  },
  {
    id: 'tempered-swap',
    number: 54,
    name: '담금질',
    nameEn: 'Tempered Swap',
    rarity: 'uncommon',
    tags: ['exchange', 'mutation'],
    glyph: '鍛',
    description: '교환으로 뽑은 카드가 이번 스테이지 동안 무작위 강화를 얻음.',
    trigger: 'EXCHANGE_USED',
    conditions: [],
    effects: [{ kind: 'custom', id: 'enhanceDrawn' }],
    shout: '담금질',
  },
  {
    id: 'twin-swap',
    number: 55,
    name: '쌍교환',
    nameEn: 'Twin Swap',
    rarity: 'uncommon',
    tags: ['exchange', 'month'],
    glyph: '換',
    description: '한 스테이지에 같은 달 카드를 두 번 교환하면 목표 점수의 8% 보너스.',
    trigger: 'EXCHANGE_USED',
    conditions: [],
    effects: [{ kind: 'custom', id: 'twinSwap' }],
  },
];
